### ISSUE TITLE
Optional Component Parameters

### ISSUE THREAD

**Issue by mattrothenberg** [trendyminds/molecule#1]
Howdy! Feature suggestion for you around optional component parameters...

### Context
I built a component called `UnderlineHeader` which takes an optional `icon` parameter. Isn't it beautiful?
```twig
{{
  craft.molecule.get("UnderlineHeader", { heading: "Articles" })
}}
```
<img width="217" alt="screen shot 2019-02-09 at 9 03 22 pm" src="https://user-images.githubusercontent.com/5148596/52528500-29e02d80-2cae-11e9-8c68-95a8253be1dc.png">

```twig
{{
  craft.molecule.get("UnderlineHeader", { heading: "Categories", icon: 'fa-tag' })
}}
```
<img width="175" alt="screen shot 2019-02-09 at 9 03 25 pm" src="https://user-images.githubusercontent.com/5148596/52528501-2cdb1e00-2cae-11e9-9d18-dcd3e4a96d0c.png">

### The Request
In the template for `UnderlineHeader`, I have to resort to some verbose `if icon is defined then icon` logic to conditionally render the icon, since I don't always pass an `icon` parameter when I use the component. I'm curious if we can get around this by allowing component authors to initialize certain parameters with `null` or `falsy` values. Does this make sense? I'm happy to add more context if need be. Perhaps I'm just confused on how to use Molecule 😛

**Comment by aaronbushnell** [comment]
Hey @mattrothenberg — this is a great question! 

So, one thing to note is **Molecule was created to sort-of mimic stateless React components**. When you use Molecule you request your component—in this case, "UnderlineHeader" and you pass all of the properties (or in React parlance, "props") to the component to be rendered. In practice this ends up being something like...

```jsx
<UnderlineHeader heading: "Categories" />
```
or
```jsx
<UnderlineHeader heading: "Categories" icon="fa-tag" />
```

In doing this, your React component needs conditional logic because sometimes `icon` is defined and sometimes it's not. So maybe you resolve this in your React component using the following:
```jsx
{props.icon && <span className={`fa ${props.icon}`} /> } {props.heading}
```

Because of this, I think it's okay to wrap your optionals in conditionals because I think this would be required in the React/JSX ecosystem, too.

## Two alternatives to consider

1. **You might consider alternative ways to pass data into props**. Maybe it makes more sense to consider the icon part of the `header` prop? Something like...

```twig
{{craft.molecule.get("UnderlineHeader", {
    header: '<span class="fa fa-tag"></span> Tags'
  })
}}
```

_FWIW, this is not how I personally would set this up, but this is an option should you want to consider an alternative_

2. **You might consider creating two different components for these cases**. Maybe you have an `UnderlineHeader` and `UnderlineHeaderIcon` component. The first has no icon, but the second one requires it.

---

Anywho—I hope that gives you a bit of background on the ideology and a couple options you might entertain here. Personally, I don't have any issues setting up something like this:

```twig
{{craft.molecule.get("UnderlineHeader", { header: "Test Header" })}}
```

```twig
<div class="UnderlineHeader">
  {% if icon is defined and icon %}
    <span class="fa {{icon}}"></span>
  {% endif %}
  
  {{heading}}
</div>
```
In fact, that's how many of mine are setup and I think that tracks pretty well with some other templating libraries!

Let me know if you have any further questions, though!

**Comment by mattrothenberg** [comment]
Makes total sense, thanks for the thorough explanation!
________________________________

**Comment by aaronbushnell** [comment]
You bet, @mattrothenberg! Please do reach out if you have any further questions or if you have any thoughts on how to improve Molecule 😊
